version: '3.4'

services:
  backend_vue_challenge:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend_vue_challenge
    environment:
      - ENV_FILE_PATH=environments/.env.dev
      - TZ=America/Manaus
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn src.api:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/backend
      - ./environments:/environments
    ports:
      - 8000:8000
    restart: 'always'